[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
# Include all files in all functions
[functions]
  included_files = ["public/**"]
