[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[functions]
  directory = "funcs"
  # Include all files in all functions
  included_files = ["src/**"]
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
